apiVersion: v2
name: syncthing
type: application
version: 0.1.4
# renovate: image=syncthing/syncthing
appVersion: "2.0.14"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
