apiVersion: v2
name: whoami
type: application
version: 0.1.1
# renovate: image=traefik/whoami
appVersion: "v1.123.7"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
