pgadmin4-helm:
  ingress:
    enabled: true
    hostname: pgadmin.192-168-178-31.sslip.io
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  serverDefinitions:
    enabled: true
    data:
      cnpg-postgres:
        Name: CNPG (postgres)
        Group: Servers
        Host: cnpg-cluster-rw
        Port: 5432
        Username: postgres
        MaintenanceDB: postgres
        Shared: true
