pgadmin4-helm:
  ingress:
    enabled: true
    hostname: pgadmin.192-168-178-31.sslip.io
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  startupProbe:
    enabled: true
    initialDelaySeconds: 45
    failureThreshold: 30
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true
  serverDefinitions:
    enabled: true
    data:
      cnpg-postgres:
        Name: postgres
        Group: CNPG
        Host: cnpg-cluster-rw
        Port: 5432
        Username: postgres
        MaintenanceDB: postgres
        Shared: true
