apiVersion: v2
name: audiobookshelf
type: application
version: 0.1.2
# renovate: image=ghcr.io/advplyr/audiobookshelf
appVersion: "2.31.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
