{{- include "common.deployment" (list . "apprise.deployment") -}}
{{- define "apprise.deployment" -}}
spec:
  template:
    spec:
      containers:
        - ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
          {{- if .Values.configSecretRef }}
          volumeMounts:
            - name: config
              mountPath: /apprise/config/{{ .Values.configSecretRef.key }}
              subPath: {{ .Values.configSecretRef.key }}
          {{- end }}
          {{- include "common.container" . | nindent 10 }}
      {{- if .Values.configSecretRef }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.configSecretRef.name }}
            items:
              - key: {{ .Values.configSecretRef.key }}
                path: {{ .Values.configSecretRef.key }}
      {{- end }}
{{- end -}}
