apiVersion: v2
name: monitoring
type: application
version: 0.1.34
dependencies:
  - name: kube-prometheus-stack
    version: "81.2.2"
    repository: oci://ghcr.io/prometheus-community/charts
  - name: prometheus-smartctl-exporter
    version: "0.16.0"
    repository: oci://ghcr.io/prometheus-community/charts
  - name: file-exporter
    version: "0.1.0"
    condition: file-exporter.enabled
