apiVersion: v2
name: monitoring
type: application
version: 0.1.14
dependencies:
  - name: kube-prometheus-stack
    version: "79.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: file-exporter
    version: "0.1.0"
    condition: file-exporter.enabled
