apiVersion: v2
name: cnpg-cluster
type: application
version: 0.1.1
# renovate: image=ghcr.io/tensorchord/cloudnative-vectorchord
appVersion: "18.0-0.5.3"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
