image:
  repository: ghcr.io/tensorchord/cloudnative-vectorchord
  tag: ""  # Defaults to chart appVersion

superuserSecret:
  name: ''

storage:
  size: 5Gi

databases: []

roles: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 2250m
    memory: 1Gi
