image:
  repository: ghcr.io/tensorchord/cloudnative-vectorchord
  tag: ""  # Defaults to chart appVersion

superuserSecret:
  name: ''

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

databases: []
