resources:
  limits:
    cpu: 4
    memory: 7Gi

database:
  hostname: cnpg-cluster-rw
  databaseName: test
  username: test
  passwordSecretName: test

extraVolumes:
  - name: test
    mountPath: /test
    hostPath: /tmp

machine-learning:
  resources:
    limits:
      cpu: 4
      memory: 7Gi
