apiVersion: v2
name: apprise
type: application
version: 0.1.5
# renovate: image=ghcr.io/egvimo/apprise-api-headless
appVersion: "0.237.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
