apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.fullname" . }}
spec:
  instances: 1
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if .Values.superuserSecret.name }}
  enableSuperuserAccess: true
  superuserSecret:
    name: {{ .Values.superuserSecret.name }}
  {{- end }}
  storage:
    size: 1Gi
  postgresql:
    parameters:
      timezone: "Europe/Berlin"
    shared_preload_libraries:
      - "vchord.so"
  {{- if .Values.databases }}
  managed:
    roles:
      {{- range .Values.databases }}
      - name: {{ .owner }}
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: {{ .passwordSecretName }}
      {{- end }}
  {{- end }}
  monitoring:
    enablePodMonitor: true
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
