apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.fullname" . }}
spec:
  instances: 1
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if .Values.superuserSecret.name }}
  enableSuperuserAccess: true
  superuserSecret:
    name: {{ .Values.superuserSecret.name }}
  {{- end }}
  storage:
    size: {{ .Values.storage.size }}
  postgresql:
    parameters:
      timezone: "Europe/Berlin"
      wal_keep_size: "128MB"
    shared_preload_libraries:
      - "vchord.so"
  {{- if .Values.roles }}
  managed:
    roles:
      {{- toYaml .Values.roles | nindent 6 }}
  {{- end }}
  monitoring:
    enablePodMonitor: true
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
