{{- $fullName := include "common.fullname" . -}}
{{- range .Values.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .database | replace "_" "-" }}
spec:
  name: {{ .database }}
  owner: {{ .owner }}
  cluster:
    name: {{ $fullName }}
  {{- if .extensions }}
  extensions:
    {{- range .extensions }}
    - name: {{ . }}
      ensure: present
    {{- end }}
  {{- end }}
{{- end }}
