apiVersion: v2
name: n8n
type: application
version: 0.1.24
# renovate: image=ghcr.io/egvimo/n8n-custom
appVersion: "2.0.2"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
