apiVersion: v2
name: n8n
type: application
version: 0.1.17
# renovate: image=ghcr.io/egvimo/n8n-custom
appVersion: "1.120.3"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
