superuserSecret:
  name: superuser

databases:
  - database: test
    owner: test
    passwordSecretName: test
    extensions:
      - vchord
      - earthdistance

resources:
  limits:
    cpu: 4
    memory: 7Gi
