superuserSecret:
  name: superuser

databases:
  - database: test
    owner: test
    extensions:
      - vchord

roles:
  - name: test
    login: true
    passwordSecret:
      name: test

resources:
  limits:
    cpu: 4
    memory: 7Gi
