debug: true
chart-repos:
  - argo=https://argoproj.github.io/argo-helm
  - cnpg=https://cloudnative-pg.github.io/charts/
  - longhorn=https://charts.longhorn.io
excluded-charts:
  - common
  - jdownloader
