debug: true
chart-repos:
  - argo=https://argoproj.github.io/argo-helm
  - authelia=https://charts.authelia.com
  - cnpg=https://cloudnative-pg.github.io/charts/
  - longhorn=https://charts.longhorn.io
  - temporal=https://go.temporal.io/helm-charts/
excluded-charts:
  - common
  - jdownloader
