apiVersion: v2
name: home-assistant
type: application
version: 0.1.9
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2025.11.3"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
