apiVersion: v2
name: cert-manager
type: application
version: 0.1.4
dependencies:
  - name: cert-manager
    version: "v1.19.4"
    repository: "https://charts.jetstack.io"
  - name: cert-manager-webhook-ionos
    version: "1.2.2"
    repository: "https://fabmade.github.io/cert-manager-webhook-ionos"
