apiVersion: v2
name: fan-control
type: application
version: 0.1.0
# renovate: image=ghcr.io/egvimo/pwm-fan-control
appVersion: "0.237.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
