apiVersion: v2
name: filebrowser
type: application
version: 0.1.9
# renovate: image=filebrowser/filebrowser
appVersion: "v2.51.2"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
