apiVersion: v2
name: filebrowser
type: application
version: 0.1.6
# renovate: image=filebrowser/filebrowser
appVersion: "v2.46.1"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
